Repository otmasolucoes/test_project, pull requests merged in 2019-04, with the labels that each got.

#3 Branch dev is now ready for tests. Needs to merge into master.
  apps/project/management/actions/api.py
  apps/project/management/actions/validators.py
  apps/views.py
  templates/base_page.html
  templates/core/authentication/logout_error.html
  test_project/urls.py
Labels: corrigido, merge

#4 Setting tasks 27 & 31 to ready.
  .idea/dataSources.xml
  .idea/runConfigurations/install_requirements.xml
  .idea/runConfigurations/pip_uninstall_.xml
  static/apps/core/authentication/components/AuthenticationComponents.js
  static/components/BaseComponents.js
  static/js/otma-validations.js
  templates/core/authentication/signup.html
Labels: corrigido, merge, refazer

#6 Finished T27 and T31, now sending to master.
  static/apps/core/authentication/components/AuthenticationComponents.js
  templates/core/authentication/base_authentication.html
Labels: merge

#7 F8
  apps/views.py
  static/apps/core/authentication/components/AuthenticationComponents.js
  static/apps/core/authentication/controllers/AuthenticationController.js
  templates/core/authentication/base_authentication_old.html
  templates/core/authentication/change_password.html
  templates/core/authentication/login_old.html
  test_project/urls.py
Labels: merge

#8 Delete idea
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dataSources.xml
  .idea/dictionaries/adenildo.xml
  .idea/runConfigurations/install_requirements.xml
  .idea/runConfigurations/pip_uninstall_.xml
Labels: merge, prioridade

#9 Sincronização da master com a dev
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dataSources.xml
  .idea/dictionaries/adenildo.xml
  .idea/runConfigurations/install_requirements.xml
  .idea/runConfigurations/pip_uninstall_.xml
Labels: merge, prioridade

#10 F8
  conf/requirements/dependencies.txt
  conf/requirements/requirements.txt
  static/apps/core/authentication/components/AuthenticationComponents.js
  templates/base_page.html
Labels: conflito, refazer

#11 Dev
  apps/views.py
  conf/requirements/dependencies.txt
  conf/requirements/requirements.txt
  static/apps/core/authentication/components/AuthenticationComponents.js
  static/apps/core/authentication/controllers/AuthenticationController.js
  templates/base_page.html
  templates/core/authentication/base_authentication_old.html
  templates/core/authentication/change_password.html
  templates/core/authentication/login_old.html
  test_project/urls.py
Labels: merge, prioridade

#12 Mandando algumas correções
  apps/views.py
  test_project/urls.py
Labels: corrigido, merge, prioridade

#14 F10
  apps/views.py
  conf/configurations.py
  conf/requirements/requirements.txt
  conf/vars/messages/email.py
  conf/vars/messages/templates/confirm_email.html
  conf/vars/messages/templates/resend_activation_code_email.html
  conf/vars/messages/templates/reset_password_email.html
  static/apps/AppComponents.js
  static/apps/AppController.js
  static/apps/core/authentication/components/AuthenticationComponents.js
  static/apps/core/authentication/controllers/AuthenticationController.js
  static/apps/core/commons/components/FormsComponents.js
  static/css/signup.css
  templates/base_page.html
  templates/core/authentication/base_authentication.html
  templates/core/authentication/change_password.html
  templates/core/authentication/login.html
  templates/core/authentication/signup.html
  test_project/settings.py
  test_project/urls.py
Labels: corrigido

#16 Sincronização da dev com a master
  README.md
Labels: merge, prioridade

#17 F13
  apps/views.py
  static/apps/core/commons/components/FormsComponents.js
  static/apps/core/entities/components/EntitiesComponents.js
  static/apps/core/entities/controllers/EntitiesController.js
  static/css/core/entities/table.css
  templates/base_page.html
  templates/core/entities/entities.html
  test_project/urls.py
Labels: conflito, prioridade
